### ISSUE TITLE
[Ideia] Mandar localização para a policia

### ISSUE THREAD

**Issue by Cristuker** [mateusmoov/nubank-for-bandido#2]
Só passou pela minha cabeça aqui, será que teria como enviar a localização para a policia ou avisa-los de alguma?

**Comment by mateusmoov** [comment]
Automatizado eu acho que não, seria melhor mesmo gravar os dados de localizacão e foto e mandar manualmente mesmo

**Comment by Cristuker** [comment]
Foi só um pensamento intrusivo que passou enquanto via o repo asuhdasd. Mas parando pra pensar agora acho que nem seria tão bom assim. Mas lembrei de outra coisa, tem um modo de perda pelo menos ios que vc consegue ver o celular em tempo real no mapa
